# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [6]:
# a =
a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [8]:
print(a)

print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [10]:
print(a[2])

300

What are the values of index for series a?

In [12]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [14]:
a.index = ['c', 'a', 'b', 'd']

print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [16]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [18]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [21]:
# b =
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])

print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [23]:
# a =
a = pd.Series([100, 200, 300, 400])

print(a)

0    100
1    200
2    300
3    400
dtype: int64

In [27]:
#print a again after appending b into it

a = pd.concat([a, b])

print(a)

0    100
1    200
2    300
3    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [29]:
# a =
a = pd.Series([100, 200, 300, 400])

print(a)

0    100
1    200
2    300
3    400
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [31]:
# df =

df = pd.DataFrame(a)

print(df)

     0
0  100
1  200
2  300
3  400

In [33]:
print(df.shape)

(4, 1)

What is the shape of the datafarme <br>
(also, what does it imply?)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [37]:
# yep its same as the series.
print(df.index)

RangeIndex(start=0, stop=4, step=1)

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [40]:
print(df.head())

print(df.tail())

     0
0  100
1  200
2  300
3  400
     0
0  100
1  200
2  300
3  400

Rename the column of the dataframe as 'points'

In [43]:
df.columns = ['points']

print(df)

   points
0     100
1     200
2     300
3     400

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [45]:
#Create fruits array

# fruits =
fruits = np.array(['Apple', 'Banana', 'Mango', 'Orange'])

print(fruits)

['Apple' 'Banana' 'Mango' 'Orange']

In [47]:
#Create series fruits out of fruits array

# fruits =
fruits = pd.Series(fruits)

print(fruits)

0     Apple
1    Banana
2     Mango
3    Orange
dtype: object

Change the index of fruits to the index of dataframe df

In [49]:
fruits.index = df.index

print(fruits)

0     Apple
1    Banana
2     Mango
3    Orange
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [51]:
df['fruits'] = fruits

print(df.head())

   points  fruits
0     100   Apple
1     200  Banana
2     300   Mango
3     400  Orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [53]:
# d1 =
d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

Print(d1)

In [55]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [57]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [59]:
city = d1['city']

print(city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

print city <br>
What is the type of city.

In [61]:
print(city)

print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [63]:
# d2 =
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})

print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [65]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [67]:
# d3 =

d3 = pd.concat([d1, d2])

print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [69]:
temp_cities = d3[d3['Temperature'] <= 20]

print(temp_cities)

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [71]:
temp_cities = d3[d3['Temperature'] >= 35]

print(temp_cities)

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [73]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =
def is_ut(x):
    if x in ['Chandigarh', 'Pondicherry', 'Delhi']:
        return True
    else:
        return False

d3['is_ut'] = d3['city'].apply(is_ut)

In [75]:
# print d3
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [77]:
# write function here
def c_to_f(temp):
    return (temp * 9/5) + 32

In [79]:
# check function c_to_f(10)
print(c_to_f(10))

50.0

In [81]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)

print(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [87]:
def is_ut(x):
    if x in ['Chandigarh', 'Pondicherry', 'Delhi']:
        return True
    else:
        return False

d1['is_ut'] = d1['city'].apply(is_ut)

print(d1)
d1_ut = d1[d1['is_ut'] == True]

print(d1_ut)

         city  Temperature  is_ut
0  Chandigarh           15   True
1       Delhi           22   True
2      Kanpur           20  False
3     Chennai           26  False
4      Manali           -2  False
         city  Temperature  is_ut
0  Chandigarh           15   True
1       Delhi           22   True

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [89]:
d1_f = d1[d1['Temperature'] > 32.22]

print(d1_f)

Empty DataFrame
Columns: [city, Temperature, is_ut]
Index: []

Select only the first three rows of the dataframe d1.

In [91]:
d1_first3 = d1.iloc[:3]

print(d1_first3)

         city  Temperature  is_ut
0  Chandigarh           15   True
1       Delhi           22   True
2      Kanpur           20  False

Select all the rows and last two columns in the dataframe.

In [93]:
d1_last2 = d1.iloc[:, -2:]

print(d1_last2)

   Temperature  is_ut
0           15   True
1           22   True
2           20  False
3           26  False
4           -2  False

## Groupby

In [95]:
# Create a dataframe using dictionary of your choice

# data =
data = {
    'Department': ['BCA', 'BCA', 'BBA', 'BBA', 'BCA', 'BBA'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Marks': [85, 90, 75, 80, 95, 88],
    'Age': [20, 21, 22, 20, 21, 22]
}

df = pd.DataFrame(data)

print(df)

  Department  Gender  Marks  Age
0        BCA    Male     85   20
1        BCA  Female     90   21
2        BBA    Male     75   22
3        BBA  Female     80   20
4        BCA    Male     95   21
5        BBA  Female     88   22

In [105]:
# Use Groupby of single column with aggregate sum()

df.groupby('Department').sum()

                      Gender  Marks  Age
Department
BBA         MaleFemaleFemale    243   64
BCA           MaleFemaleMale    270   62

In [103]:
# Use Groupby of single column with aggregate count()

df.groupby('Department').count()

            Gender  Marks  Age
Department
BBA              3      3    3
BCA              3      3    3

In [101]:
# Use Groupby of single column with aggregate min() and max()

df.groupby('Department').agg(['min','max'])

            Gender       Marks     Age
               min   max   min max min max
Department
BBA         Female  Male    75  88  20  22
BCA         Female  Male    85  95  20  21

In [107]:
# Use Groupby of any 2 columns with aggregate mean()

df.groupby(['Department','Gender']).mean(numeric_only=True)

                   Marks   Age
Department Gender
BBA        Female   84.0  21.0
           Male     75.0  22.0
BCA        Female   90.0  21.0
           Male     90.0  20.5

In [109]:
# Use Groupby of any 2 columns with aggregate min() and max()

df.groupby(['Department','Gender']).agg(['min','max'])

                  Marks     Age
                    min max min max
Department Gender
BBA        Female    80  88  20  22
           Male      75  75  22  22
BCA        Female    90  90  21  21
           Male      85  95  20  21